version: '3'
services:
  redis:
    image: redis:7.0.4
  bot:
    build: .
    depends_on:
      - redis
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: r2dbc:postgresql://postgres:5432/counting
      DATABASE_USERNAME: counting
      DATABASE_PASSWORD: counting
      REDIS_HOST: redis